# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- ### index
    - 배열내의 원소의 식별번호
    - 0부터 시작 
- ### indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- ### 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
    - N차원 배열의 경우
        - arr[0축 index, 1축 index, ..., n축 index]
- ### 팬시(fancy) 인덱싱
    - **여러개의 원소를 한번에 조회**할 경우 리스트에 담아 전달한다.
    - 다차원 배열의 경우 각 축별로 list로 지정
    - `arr[[1,2,3,4,5]]`
        - 1차원 배열(vector): 1,2,3,4,5 번 index의 원소들 한번에 조회
    - `arr[[0,3],[ 1,4]]`
        - [0,3] - 1번축 index list, [1,4] - 2번축 index list
        - 2차원 배열(matrix): [0,1], [3,4] 의 원소들 조회

In [2]:
import numpy as np

a1=np.arange(10)
a1.shape
# 1차원배열 - axis(축)이 한개 -> 지정할 수 있는 index도 1개

(10,)

In [3]:
print("한개:", a1[0],a1[5])

한개: 0 5


In [4]:
print('여러개(3,6,7)-fancy indexing:',a1[[3,6,7]])

여러개(3,6,7)-fancy indexing: [3 6 7]


In [5]:
print('음수index:', a1[-1])

음수index: 9


In [7]:
print(a1[[-1,9,-2,8]])

[9 9 8 8]


In [8]:
# 변경
a1[0] = 100
a1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [9]:
a1[[0,1,2]] = 10000 # 여러 index의 값을 한번에 변경
a1

array([10000, 10000, 10000,     3,     4,     5,     6,     7,     8,
           9])

In [13]:
a1[[3,5,7]] = [700,800,900] # 여러 index의 값을 서로 다른 값으로 변경
a1

array([10000, 10000, 10000,   700,     4,   800,     6,   900,     8,
           9])

In [17]:
# 다차원(2차원이상) 배열조회
# [ , , , ] , 를 기준으로 각 축별로 index를 지정
a2 = np.arange(30).reshape(5,6)
print(a2.shape)
a2

(5, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
#a2[0축 index, 1축의 index]

In [22]:
a2[0]

array([0, 1, 2, 3, 4, 5])

In [21]:
a2[2]

array([12, 13, 14, 15, 16, 17])

In [24]:
a2[0,3], a2[4,5]

(3, 29)

In [25]:
a2[[2,3,4],[1,1,2]] #0축들,1축들

array([13, 19, 26])

In [26]:
a3 = np.arange(24).reshape(3,4,2)
print(a3.shape)
a3

(3, 4, 2)


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [31]:
a3[0] #0축의 첫번째

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [32]:
a3[2]

array([[16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [34]:
a3[2,1] #0축의 2 index, 1번축의 1 index

array([18, 19])

In [35]:
a3[2,1,0]

18

In [36]:
a3.shape

(3, 4, 2)

In [37]:
a3[0].shape

(4, 2)

In [39]:
a3[0,0].shape


(2,)

In [40]:
a3[0,[1,2],[1,0]]

array([3, 4])

## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ]
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1)

In [42]:
a1 = np.arange(100)
print(a1.shape)
a1[5:20] #5~20-1, step:1

(100,)


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
a1[-5:] # -5 ~ 마지막

array([95, 96, 97, 98, 99])

In [44]:
a1[:10] # 0~ 10-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a1[5:75:5] # 5~75-1: step:5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

In [50]:
print(a2.shape)
a2

(5, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
#a2[0축,1축]
a2[:3]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [55]:
a2[1:4,1:5]

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22]])

In [56]:
a2[1:4,3] #0축:slicing, 1축: indexing

array([ 9, 15, 21])

In [57]:
a2[1:4,[2,4,5]]

array([[ 8, 10, 11],
       [14, 16, 17],
       [20, 22, 23]])

In [60]:
a3.shape
a3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [59]:
a3[2, :3,[0,1]]

array([[16, 18, 20],
       [17, 19, 21]])

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
        - `arr[:3, :]`
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용
- 다차원의 경우
    - arr[0축 slicing, 1축 slicing, ..., n축 slicing]
- slicing과 indexing 문법은 같이 쓸 수 있다.
- 모든 축에 index를 지정할 필요는 없다.

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다.
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성
    - 복사후 처리하면 원본이 바뀌지 않는다.

In [61]:
b = a1[:10]
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
b[0] = 1000
b

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [65]:
b2 = a1[:10].copy() #copy() 깊은복사 (depp copy)
b2[0] = 50000
b2

array([50000,     1,     2,     3,     4,     5,     6,     7,     8,
           9])

In [66]:
a1

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99])

## boolean indexing
- Index 연산자에 Boolean 배열을 넣으면 True인 index의 값만 조회 (False가 있는 index는 조회하지 않는다.)
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [73]:
a = np.arange(1,10)
b = np.random.choice([True,False], size=9)

In [74]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
b

array([False,  True, False,  True,  True,  True,  True, False,  True])

In [67]:
# and: &, or: |, not: ~
# 파이썬 and, or, not 키워드 연선자는 사용안됨.(넘파이,판다스)
# 피연산자는 ()로 묶어준다.(넘파이, 판다스)

In [77]:
a[(a<5)|(a>7)]

array([1, 2, 3, 4, 8, 9])

In [79]:
b = np.arange(12).reshape(4,3)
print(b.shape)
b

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
b>4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### np.where()
- np.where(boolean 배열) - True인 index를 반환
- boolean연산과 같이쓰면 특정 조건을 만족하는 원소의 index조회됨.
- np.where(booean 배열, True를 대체할 값, False를 대체할 값)
    - True와 False를 다른 값으로 변경한다.

In [82]:
np.where([True,False,True]) # True의 index들을 ndarray로 묶어서 반환. 반환타입:tuple (축별로 묶어서 반환)

(array([0, 2]),)

In [84]:
np.where([[True,False],[True,False]])
#[0,1] : 0축의 index들, [0,0] : 1축의 index들 ===> (실제 값의 index는 같은 index끼리 묶어준다.)(0,0)(1,0)

(array([0, 1]), array([0, 0]))

- 2차원도 마찬가지
    - 단 where는 축별로 배열이 반환된다. [0,1], [2,3] => (0,2)  (1,3)
    - 보통 Vector에 적용한다.

In [85]:
# boolean indexing: 조건을 만족하는 값을 조회
# where(): 조건을 만족하는 값들의 위치(index)를 조회
idx1, idx2 = np.where(b>5)

In [86]:
for o,t in zip(idx1,idx2):
    print(o,t,sep=",")

2,0
2,1
2,2
3,0
3,1
3,2


In [87]:
#True, False 를 다른 값으로 변경
np.where(a>5, '5이상','5미만')

array(['5미만', '5미만', '5미만', '5미만', '5미만', '5이상', '5이상', '5이상', '5이상'],
      dtype='<U3')

In [89]:
np.where(a>5,"5이상",a) # vlaue자리에 배열객체를 넣으면 비교한 조건의 값이 그대로 나온다.

array(['1', '2', '3', '4', '5', '5이상', '5이상', '5이상', '5이상'], dtype='<U21')

cf) 서로 다른 타입을 같은 타입으로 통일할때 우선순위 

논리형 < 정수 < 실수 < 문자열

### 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환

In [90]:
# 특정조건을 만족하는 값이 하나라도 있는지 확인 -> any()
# 특정조건을 배열의 모든 원소가 만족하는지 확인 -> all()
np.any(a > 5)


True

In [91]:
np.all(a > 5)

False

### 정렬
- np.sort(arr): arr을 정렬
- np.argsort(arr): 정렬 후 index를 반환

In [92]:
x = np.random.randint(10,20,10)

In [95]:
y = np.sort(x)
y
#x 를 정렬한 새로운 배열을 반환(원본을 정렬하지 않는다.)
# 오름차순 정렬

array([12, 12, 12, 13, 14, 14, 15, 16, 17, 18])

In [97]:
#내림차순 정렬 - sort()로 정렬한 뒤에서 reverse시킨다.
y2 = np.sort(x)[::-1]
y2

array([18, 17, 16, 15, 14, 14, 13, 12, 12, 12])

In [99]:
-np.sort(-x)

array([18, 17, 16, 15, 14, 14, 13, 12, 12, 12])

In [100]:
#배열객체.sort() => 원본이 정렬
x.sort()

In [101]:
x

array([12, 12, 12, 13, 14, 14, 15, 16, 17, 18])

In [102]:
x2 = np.random.randint(10,20,size=(5,4))
print(x2.shape)
x2

(5, 4)


array([[16, 15, 10, 17],
       [19, 16, 12, 10],
       [19, 17, 13, 19],
       [15, 17, 10, 11],
       [19, 17, 16, 19]])

In [104]:
np.sort(x2,axis=0)

array([[15, 15, 10, 10],
       [16, 16, 10, 11],
       [19, 17, 12, 17],
       [19, 17, 13, 19],
       [19, 17, 16, 19]])

In [105]:
np.sort(x2,axis=1)

array([[10, 15, 16, 17],
       [10, 12, 16, 19],
       [13, 17, 19, 19],
       [10, 11, 15, 17],
       [16, 17, 19, 19]])

In [107]:
x3 = np.random.randint(10,20,10)
x3

array([15, 11, 15, 15, 16, 14, 17, 13, 19, 18])

In [109]:
np.argsort(x3)
#정렬한 것을 index로 반환.

array([1, 7, 5, 0, 2, 3, 4, 6, 9, 8])

In [110]:
np.sort(x3)

array([11, 13, 14, 15, 15, 15, 16, 17, 18, 19])