# 배열의 형태(shape) 변경
- 형태를 바꿀때 전체 원소의 개수가 바뀔 수 없다.

## reshape()을 이용한 차원 변경
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
        - 원소의 개수를 유지하는 shape으로만 변환 가능하다.

In [2]:
import numpy as np
a= np.arange(20)
print(a.shape) # 1차원 배열, (20,)
print(a.size)
a

(20,)
20


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
# a -> 2차원 (2,5)
a2 = np.reshape(a,(4,5))
print(a2.shape)
print(a2.size)

(4, 5)
20


In [4]:
# a -> 3차원 (2,2,5)
a3 = np.reshape(a,(2,2,5))
print(a3.shape)
print(a3.size)

(2, 2, 5)
20


In [5]:
a4 = a.reshape((2,2,5))
a4.shape, a4.size

((2, 2, 5), 20)

In [6]:
a5 = a.reshape(4,5)
a5.shape, a5.size

((4, 5), 20)

In [7]:
a5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
#축을 지정할 때 하나의 축의 size를 -1로 줄 수있다. -1을 주면 나머지 size를 그 축의 size로 지정한다.
a6 = a.reshape(2,2,-1)
a6.shape,a6.size

((2, 2, 5), 20)

In [10]:
a7 = a6.reshape(20) #3차원 -> 1차원 배열
a7.shape

(20,)

In [12]:
# a6.reshape(2,4) #a6의 size와 (2,4) 배열의 size가 다르기 때문에 Exception 발생.

## 차원 늘리기(확장)

### numpy.newaxis 속성을 이용해 차원 늘리기
- size가 1인 rank를 늘릴때 사용한다. 
    - 지정한 axis에 size 1인 축을 추가한다.
- slicing에 사용하거나 indexing에 `...`과 같이 사용한다.
    - slicing의 경우 원하는 위치의 축을 늘릴 수 있다.
    - index에 ...과 사용하는 경우 첫번째나 마지막 축을 늘릴때 사용한다.
    

In [13]:
x = np.arange(1,6)
print(x.shape)
x

(5,)


array([1, 2, 3, 4, 5])

In [14]:
#newaxis와 slicing 연산자를 이용해 늘리기.
x2 = x[:,np.newaxis]
print(x2.shape)

(5, 1)


In [ ]:
x3 = x[np.new]

In [16]:
x4 = np.arange(20).reshape(2,2,5)
print(x4.shape)
x4

(2, 2, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [19]:
# (2,2,5) => (1,2,2,5) [:] : - 축별로 순서대로 지정해야 한다.
x5 = x4[np.newaxis, :,:,:]
print(x5.shape)

(1, 2, 2, 5)


In [22]:
x6 = x4[:,:,:,np.newaxis]
x6.shape

(2, 2, 5, 1)

In [23]:
# (2,2,5) -> (2,2,1,5)
x7 = x4[:,:,np.newaxis,:]
x7.shape

(2, 2, 1, 5)

### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능

In [24]:
x4.shape

(2, 2, 5)

In [25]:
# (2,2,5) -> (1,2,2,5) 앞에 더미축을 추가
x8 = x4[np.newaxis, ...]
x8.shape

(1, 2, 2, 5)

In [27]:
# (2,2,5) -> (2,2,5,1) 뒤에 더미축을 추가
x9 = x4[...,np.newaxis]
x9.shape

(2, 2, 5, 1)

### numpy.expand_dims (배열, axis)
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장한다.

In [28]:
x4.shape

(2, 2, 5)

In [30]:
x10 = np.expand_dims(x4,axis=0)
x10.shape

(1, 2, 2, 5)

In [31]:
x11 = np.expand_dims(x4,axis=1)
x11.shape

(2, 1, 2, 5)

In [33]:
x12 = np.expand_dims(x4,axis=-1) #axis = -1 뒤에서 첫번째 축
x12.shape

(2, 2, 5, 1)

## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다.
- 제거하려는 축의 size는 1이어야 한다.
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3,1,1,2) => (3,2)

In [34]:
x11.shape

(2, 1, 2, 5)

In [35]:
y = x11.squeeze()
y.shape

(2, 2, 5)

In [36]:
x = np.arange(20).reshape(1,2,1,2,1,5,1)
x.shape

(1, 2, 1, 2, 1, 5, 1)

In [37]:
y2=x.squeeze(axis=0) #0축을 제거
y2.shape

(2, 1, 2, 1, 5, 1)

In [38]:
y3 = x.squeeze(axis=2)
y3.shape

(1, 2, 2, 1, 5, 1)

In [39]:
# x.squeeze(axis=1) #1번축은 dummy 축이 아니기 때문에 예외 발생.

In [41]:
y4= x.squeeze() #축을 지정하지 않으면 dummy axis는 모두 제거.
y4.shape

(2, 2, 5)

### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다.

In [42]:
print(y4.shape)
y5 = y4.flatten()
y5.shape

(2, 2, 5)


(20,)

In [43]:
y4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [44]:
y5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
x11.shape
y6 = x11.flatten()
y6.shape

(20,)

## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 마지막 index에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가. 
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

### append()

In [46]:
a = np.arange(3)
print(a.shape)
a

(3,)


array([0, 1, 2])

In [47]:
# append() 맨뒤에 추가
np.append(a,100)

array([  0,   1,   2, 100])

In [48]:
np.append(a,[200,300,400]) #동시에 여러개 값을 추가

array([  0,   1,   2, 200, 300, 400])

In [49]:
a2 = np.arange(12).reshape(4,3)
print(a2.shape)
a2

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#append()축을 지정. 축을 생략하면 flatten(1차원으로 변환) 후 append처리한다.
#추가할 값은 지정한 축의 값과 같은 shape으로 넣어줘야 한다.


In [ ]:
np.append(a2,100)

In [54]:
np.append(a2,
         [
             [100,200,300],
             [1000,2000,3000]
         ],axis=0)

array([[   0,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [55]:
np.append(a2,
         [[11],[22],[33],[44]]
        ,axis = 1)

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 22],
       [ 6,  7,  8, 33],
       [ 9, 10, 11, 44]])

In [56]:
np.append(a2,
         [[11,111,1111],[22,222,2222],[33,333,3333],[44,444,4444]]
        ,axis = 1)

array([[   0,    1,    2,   11,  111, 1111],
       [   3,    4,    5,   22,  222, 2222],
       [   6,    7,    8,   33,  333, 3333],
       [   9,   10,   11,   44,  444, 4444]])

### insert

In [57]:
print(a.shape)
a

(3,)


array([0, 1, 2])

In [60]:
# 배열, index, 값
np.insert(a,0,100)

array([100,   0,   1,   2])

In [61]:
a

array([0, 1, 2])

In [62]:
np.insert(a,1,1000)

array([   0, 1000,    1,    2])

In [65]:
np.insert(a,0,[100,200,300]) #하나의 index에 여러개의 값 추가.

array([100, 200, 300,   0,   1,   2])

In [67]:
np.insert(a,[0,2],[1000,2000]) #여러 index에 값들을 삽입

array([1000,    0,    1, 2000,    2])

In [68]:
np.insert(a,[0,2],5000)

array([5000,    0,    1, 5000,    2])

In [69]:
#다차원 배열 insert
np.insert(a2,2,100000) # axis를 지정안함 => flatten(1차원으로 변경)후에 insert

array([     0,      1, 100000,      2,      3,      4,      5,      6,
            7,      8,      9,     10,     11])

In [70]:
np.insert(a2,2,[[10,20,30]], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
np.insert(a2,2,[[10,20,30],[100,200,300]], axis = 0)

array([[  0,   1,   2],
       [  3,   4,   5],
       [ 10,  20,  30],
       [100, 200, 300],
       [  6,   7,   8],
       [  9,  10,  11]])

In [74]:
np.insert(a2,2,
         [[1,2,3,4],[10,20,30,40]],
         axis=1)

array([[ 0,  1,  1, 10,  2],
       [ 3,  4,  2, 20,  5],
       [ 6,  7,  3, 30,  8],
       [ 9, 10,  4, 40, 11]])

In [76]:
np.insert(a2,1,10, axis=0) #동일한 값을 insert할 경우 정수로 지정.

array([[ 0,  1,  2],
       [10, 10, 10],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [77]:
np.insert(a2,1,10, axis=1)

array([[ 0, 10,  1,  2],
       [ 3, 10,  4,  5],
       [ 6, 10,  7,  8],
       [ 9, 10, 10, 11]])

### delete

In [78]:
#배열 , index
a = np.delete(a,0)

array([1, 2])

In [80]:
#다차원 배열에서 원소삭제
# axis 를 지정 (기본-flatten후에 삭제)

np.delete(a2,2)


array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
r = np.delete(a2, 1, axis=0)
a2.shape,r.shape

((4, 3), (3, 3))

In [83]:
r = np.delete(a2, [0,2], axis=0)
print(a2.shape,r.shape)
r

(4, 3) (2, 3)


array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [84]:
r = np.delete(a2, 2, axis=1)
print(a2.shape,r.shape)
r

(4, 3) (4, 2)


array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [85]:
r = np.delete(a2, np.s_[:2] , axis=1)
print(a2.shape,r.shape)
r

(4, 3) (4, 1)


array([[ 2],
       [ 5],
       [ 8],
       [11]])

In [86]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## 배열 합치기
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다. ==> 같은 rank(차원)의 배열끼리만 합칠수 있다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의 개수(rank) 은 같아야 한다.
    - axis속성으로 지정한 축 이외의 축의 크기가 같아야 한다.
    - 결과의 축의개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- ### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.

### concatenate()

- axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남)붙는다.)
    - 그래서 각 배열의 컬럼 수가 같아야 한다. 
- axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙는다.)
    - 그래서 각 배열의 행수가 같아야 한다.

In [93]:
a = np.arange(10)
b = np.arange(100,110)
c = np.arange(1000,1005)
print(a.shape,b.shape,c.shape)

(10,) (10,) (5,)


In [94]:
# 1차원 배열들 -> axis: 0=> 합치는 기준: 0
r = np.concatenate([a,b,c])
print(r.shape)
r

(25,)


array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,  100,
        101,  102,  103,  104,  105,  106,  107,  108,  109, 1000, 1001,
       1002, 1003, 1004])

In [95]:
a = np.arange(12).reshape(4,3)
b = np.arange(100,112).reshape(4,3)
print(a.shape,b.shape)

(4, 3) (4, 3)


In [98]:
#2차원 배열 -> axis:0,1
r = np.concatenate([a,b])#axis=0
print(r.shape) #(8,3)
r

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [101]:
r = np.concatenate([b,a], axis=1)
print(r.shape) #(4,6)
r

(4, 6)


array([[100, 101, 102,   0,   1,   2],
       [103, 104, 105,   3,   4,   5],
       [106, 107, 108,   6,   7,   8],
       [109, 110, 111,   9,  10,  11]])

In [105]:
c = np.arange(6).reshape(2,3)
print(a.shape,b.shape,c.shape)
# a와c를 합치기 -> axis = 1 
r = np.concatenate([a,c], axis = 0)
r.shape

(4, 3) (4, 3) (2, 3)


(6, 3)

In [106]:
r = np.concatenate([a,c], axis = 1) #합치는 기준축을 제외한 나머지 축의 size는 같아야 한다.

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [108]:
x = np.arange(3*5*5).reshape(3,5,5)
y = np.arange(100,175).reshape(3,5,5)

# 3차원 : axis - 0 , 1, 2
r=np.concatenate([x,y],axis=0) 
print(r.shape)

(6, 5, 5)


In [109]:
r=np.concatenate([x,y],axis=2) 
print(r.shape) #(3,5,10)
r

(3, 5, 10)


array([[[  0,   1,   2,   3,   4, 100, 101, 102, 103, 104],
        [  5,   6,   7,   8,   9, 105, 106, 107, 108, 109],
        [ 10,  11,  12,  13,  14, 110, 111, 112, 113, 114],
        [ 15,  16,  17,  18,  19, 115, 116, 117, 118, 119],
        [ 20,  21,  22,  23,  24, 120, 121, 122, 123, 124]],

       [[ 25,  26,  27,  28,  29, 125, 126, 127, 128, 129],
        [ 30,  31,  32,  33,  34, 130, 131, 132, 133, 134],
        [ 35,  36,  37,  38,  39, 135, 136, 137, 138, 139],
        [ 40,  41,  42,  43,  44, 140, 141, 142, 143, 144],
        [ 45,  46,  47,  48,  49, 145, 146, 147, 148, 149]],

       [[ 50,  51,  52,  53,  54, 150, 151, 152, 153, 154],
        [ 55,  56,  57,  58,  59, 155, 156, 157, 158, 159],
        [ 60,  61,  62,  63,  64, 160, 161, 162, 163, 164],
        [ 65,  66,  67,  68,  69, 165, 166, 167, 168, 169],
        [ 70,  71,  72,  73,  74, 170, 171, 172, 173, 174]]])

### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. 
- axis=0과 동일

In [110]:
a.shape, a.shape

((4, 3), (4, 3))

In [111]:
r = np.vstack([a,b])
print(r.shape)
r

(8, 3)


array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다.
- axis=1과 동일

In [112]:
r = np.hstack([a,b])
print(r.shape)
r

(4, 6)


array([[  0,   1,   2, 100, 101, 102],
       [  3,   4,   5, 103, 104, 105],
       [  6,   7,   8, 106, 107, 108],
       [  9,  10,  11, 109, 110, 111]])

## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. 
    - 반환값: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

In [113]:
a = np.arange(10)
a.shape

(10,)

In [ ]:
r = np.split(a,2)#a배열을통한

## hsplit()/vsplit()
- 2차원 배열을 분할

In [114]:
r1,r2,r3 = np.hsplit(x,[3,5]) #axis=1
print(r1.shape, r2.shape, r3.shape)


(3, 3, 5) (3, 2, 5) (3, 0, 5)
