# 배열을 파일에 저장 및 불러오기
- ## 바이너리 파일로 저장/불러오기
    - ### np.save("파일경로", 배열)
        - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
        - 파일명에 확장자로 npy를 붙인다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로") 
        - 파일에 저장된 배열을 불러온다.
    - ### np.savez("파일경로", 이름=배열, 이름=배열, ...)
        - 여러개의 배열을 저장할 때 사용
        - 파일명에 확장자로 npz가 붙는다.
        - 내부적으로 압축해서 저장한다.
        - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기
    - ### savetxt("파일경로", 배열 [, delimiter='공백') 
        - 텍스트 형태로 저장.
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
        - 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)
    - ### loadtxt("파일경로" [,dtype=float, delimiter=공백)

In [2]:
import numpy as np

a = np.array([1,5,8,9,10]) #1차원
b = np.ones(shape=(3,4,2)) #3차원
c = np.random.normal(size=(5,10)) # 2차원

print(a.shape,b.shape,c.shape)

(5,) (3, 4, 2) (5, 10)


In [5]:
# 저장 - binary 형식으로 저장
import os
#저장할 디렉토리가 없으면 만들어라.
save_dir = 'save_data'
if not os.path.isdir(save_dir): #save_data 디렉토리가 있는지 여부확인 - 디렉토리가 없으면
    os.mkdir(save_dir) # 디렉토리 생성.
np.save("save_data/a",a) #a배열을 save_data/a.npy 파일에 저장

In [6]:
np.save('save_data/b',b)
np.save('save_data/c',c)

In [8]:
#binary 로 저장된 배열을 불러오기
a2 = np.load('save_data/a.npy')
print(a2.shape)
a2

(5,)


array([ 1,  5,  8,  9, 10])

In [10]:
b2 = np.load('save_data/b.npy')
print(b2.shape)
b2

(3, 4, 2)


array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [11]:
c2 = np.load('save_data/c.npy')
print(c2.shape)
c2

(5, 10)


array([[ 0.5793161 , -0.8568769 , -0.38669086,  0.95293131, -1.84663023,
        -1.4343885 , -0.90870299,  0.84631124, -1.46766866, -1.27941433],
       [-1.4423108 ,  0.02825216, -0.1555076 , -0.99762964, -0.74473928,
         0.58845461, -0.31737627, -1.3659086 , -0.94990046,  0.55619625],
       [ 1.02573556, -0.28290789, -0.81719981,  0.62184495, -1.10009356,
         1.19727401, -0.66305228, -0.73511746,  0.06524503,  0.46659259],
       [-1.46001598,  0.3833    ,  0.92902915, -0.70496065, -1.67430539,
        -1.36621823, -2.19808213,  0.86302435, -0.46906068, -1.43744676],
       [ 1.81884538,  1.59591718,  0.24204996, -0.10700955, -0.87447706,
         1.16493187, -0.28370816,  0.06062419, -0.67440202,  0.92814157]])

In [12]:
# 세개의 배열을 한파일에 저장(N개를 한파일에 저장)
np.savez('save_data/all',arr_a=a, arr_b=b, arr_c=c)

In [14]:
# npz파일 읽어오기 -> load()
arr_all = np.load('save_data/all.npz')
arr_all

In [15]:
#저장할때 지정한 이름 조회
arr_all.files

['arr_a', 'arr_b', 'arr_c']

In [16]:
a3 = arr_all['arr_a']
b3 = arr_all['arr_b']
c3 = arr_all['arr_c']

In [17]:
a3

array([ 1,  5,  8,  9, 10])

In [18]:
#텍스트파일로 저장 => 1차원, 2차원 배열만 가능
np.savetxt("save_data/a_txt.csv",a,delimiter=',')

In [22]:
np.savetxt('save_data/c.csv',c)

In [23]:
np.savetxt('save_data/c_2.csv',c,delimiter=',')

In [24]:
c4 = np.loadtxt('save_data/c.csv')
c4.shape
c4

array([[ 0.5793161 , -0.8568769 , -0.38669086,  0.95293131, -1.84663023,
        -1.4343885 , -0.90870299,  0.84631124, -1.46766866, -1.27941433],
       [-1.4423108 ,  0.02825216, -0.1555076 , -0.99762964, -0.74473928,
         0.58845461, -0.31737627, -1.3659086 , -0.94990046,  0.55619625],
       [ 1.02573556, -0.28290789, -0.81719981,  0.62184495, -1.10009356,
         1.19727401, -0.66305228, -0.73511746,  0.06524503,  0.46659259],
       [-1.46001598,  0.3833    ,  0.92902915, -0.70496065, -1.67430539,
        -1.36621823, -2.19808213,  0.86302435, -0.46906068, -1.43744676],
       [ 1.81884538,  1.59591718,  0.24204996, -0.10700955, -0.87447706,
         1.16493187, -0.28370816,  0.06062419, -0.67440202,  0.92814157]])

In [27]:
c5 = np.loadtxt('save_data/c_2.csv',delimiter=',') #delimiter는 저장할 때 지정한 것과 동일한 것을 지정한다.
c5.shape
c5

array([[ 0.5793161 , -0.8568769 , -0.38669086,  0.95293131, -1.84663023,
        -1.4343885 , -0.90870299,  0.84631124, -1.46766866, -1.27941433],
       [-1.4423108 ,  0.02825216, -0.1555076 , -0.99762964, -0.74473928,
         0.58845461, -0.31737627, -1.3659086 , -0.94990046,  0.55619625],
       [ 1.02573556, -0.28290789, -0.81719981,  0.62184495, -1.10009356,
         1.19727401, -0.66305228, -0.73511746,  0.06524503,  0.46659259],
       [-1.46001598,  0.3833    ,  0.92902915, -0.70496065, -1.67430539,
        -1.36621823, -2.19808213,  0.86302435, -0.46906068, -1.43744676],
       [ 1.81884538,  1.59591718,  0.24204996, -0.10700955, -0.87447706,
         1.16493187, -0.28370816,  0.06062419, -0.67440202,  0.92814157]])

In [28]:
np.savetxt('test',b) #b: 3차원배열 => text로 저장은 1,2차원만 가능

ValueError: Expected 1D or 2D array, got 3D array instead

In [29]:
a.dtype

dtype('int64')

In [30]:
a5 = np.loadtxt('save_data/a_txt.csv', dtype='int32')
a5.dtype

dtype('int32')

In [31]:
import pandas as pd
df = pd.read_csv('save_data/c_2.csv', header=None)
df

0         1         2         3         4         5         6  \
0  0.579316 -0.856877 -0.386691  0.952931 -1.846630 -1.434389 -0.908703   
1 -1.442311  0.028252 -0.155508 -0.997630 -0.744739  0.588455 -0.317376   
2  1.025736 -0.282908 -0.817200  0.621845 -1.100094  1.197274 -0.663052   
3 -1.460016  0.383300  0.929029 -0.704961 -1.674305 -1.366218 -2.198082   
4  1.818845  1.595917  0.242050 -0.107010 -0.874477  1.164932 -0.283708   

          7         8         9  
0  0.846311 -1.467669 -1.279414  
1 -1.365909 -0.949900  0.556196  
2 -0.735117  0.065245  0.466593  
3  0.863024 -0.469061 -1.437447  
4  0.060624 -0.674402  0.928142